import type { SeedAsset } from "./types";

/** One example per category — keep the first load light. */
export const SEED_ASSETS: SeedAsset[] = [
  {
    id: "seed-sample-hero",
    name: "Sample hero",
    slug: "sample-hero",
    category: "characters",
    tags: ["example", "character"],
    width: 320,
    height: 400,
    png: "/library/characters/sample-hero.svg",
    webp: "/library/characters/sample-hero.svg",
    pngBytes: 1200,
    webpBytes: 1200,
    transparent: true,
  },
  {
    id: "seed-sample-prop",
    name: "Sample crate",
    slug: "sample-crate",
    category: "props",
    tags: ["example", "prop"],
    width: 280,
    height: 280,
    png: "/library/props/sample-crate.svg",
    webp: "/library/props/sample-crate.svg",
    pngBytes: 900,
    webpBytes: 900,
    transparent: true,
  },
  {
    id: "seed-sample-backdrop",
    name: "Sample backdrop",
    slug: "sample-backdrop",
    category: "backgrounds",
    tags: ["example", "scene"],
    width: 640,
    height: 360,
    png: "/library/backgrounds/sample-backdrop.svg",
    webp: "/library/backgrounds/sample-backdrop.svg",
    pngBytes: 1100,
    webpBytes: 1100,
    transparent: false,
  },
  {
    id: "seed-sample-house",
    name: "Sample house",
    slug: "sample-house",
    category: "buildings",
    tags: ["example", "building"],
    width: 320,
    height: 360,
    png: "/library/buildings/sample-house.svg",
    webp: "/library/buildings/sample-house.svg",
    pngBytes: 1000,
    webpBytes: 1000,
    transparent: true,
  },
  {
    id: "seed-sample-cart",
    name: "Sample cart",
    slug: "sample-cart",
    category: "vehicles",
    tags: ["example", "vehicle"],
    width: 360,
    height: 240,
    png: "/library/vehicles/sample-cart.svg",
    webp: "/library/vehicles/sample-cart.svg",
    pngBytes: 950,
    webpBytes: 950,
    transparent: true,
  },
  {
    id: "seed-sample-sheet",
    name: "Sample sheet",
    slug: "sample-sheet",
    category: "spritesheets",
    kind: "spritesheet",
    tags: ["example", "sheet", "2x2"],
    width: 256,
    height: 256,
    png: "/library/spritesheets/sample-sheet.svg",
    webp: "/library/spritesheets/sample-sheet.svg",
    pngBytes: 800,
    webpBytes: 800,
    transparent: true,
    cols: 2,
    rows: 2,
  },
  {
    id: "seed-sample-pickup",
    name: "Sample coin",
    slug: "sample-coin",
    category: "other",
    tags: ["example", "pickup"],
    width: 200,
    height: 200,
    png: "/library/other/sample-coin.svg",
    webp: "/library/other/sample-coin.svg",
    pngBytes: 700,
    webpBytes: 700,
    transparent: true,
  },
  {
    id: "seed-how-to-note",
    name: "How to pack a kit",
    slug: "how-to-pack-a-kit",
    category: "docs",
    kind: "doc",
    tags: ["guide", "kit"],
    width: 0,
    height: 0,
    png: "/library/docs/how-to-pack-a-kit.md",
    webp: "/library/docs/how-to-pack-a-kit.md",
    pngBytes: 420,
    webpBytes: 420,
    transparent: false,
    originalType: "text/markdown",
    excerpt:
      "Drop files, convert stills to WebP, pick a kit, download the zip. One example ships per category.",
  },
];
